version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www

        volumes:
            - ./:/var/www
            - ./dock-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    webserver:
        image: nginx
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8100:80"
            - "8143:443"
        volumes:
            - ./:/var/www
            - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        image: mariadb:10.5.6
        container_name: db
        restart: unless-stopped
        tty: true

        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: 123456

        volumes:
            - mariadbdata:/var/lib/mysql
            - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80" # Change port to avoid conflict with webserver
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: 123456
        networks:
            - app-network

volumes:
    mariadbdata:
        driver: local
networks:
    app-network:
        driver: bridge
